### ISSUE TITLE
Socket connection with port to <url>:8080

### ISSUE THREAD

**Issue by Rinma** [thecodingmachine/workadventure#574]
Hi,

I have workadventure running on my server and I have problems with the sockjs connection.
In the console of my browser, I can see a CORS error because the socket connection is going to <url>:8080 and I don't know why. In the docker-compose, I set all env variables without ports.

Error in Browser: 
- `map.json:1 - Access to XMLHttpRequest at 'https://play.adventure.<url>:8080/sockjs-node/info?t=1610049599890' from origin 'https://play.adventure.<url>' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`
- `sockjs.js:1606 - GET https://play.adventure.<url>:8080/sockjs-node/info?t=1610049599890 net::ERR_FAILED`

The only issue I found so far is that the text chat is not working

**Comment by Informatic** [comment]
If I understand correctly, this is mostly caused by your instance running in developer mode, which adds some autoreload code, which uses that additional sockjs channel.

I don't think there's any "production-ready" deployment setup here yet, is there?

**Comment by moufmouf** [comment]
Yup! If you use the Dockerfiles at hub.docker.com, you should not have the issue.
Otherwise, in docker-compose, you need to "yarn run build" the files in the "front" container and then use a classic webserver to serve those files instead of running "yarn run start"

**Comment by loelkes** [comment]
> Yup! If you use the Dockerfiles at hub.docker.com, you should not have the issue.

I did:
1. `docker build -f front/Dockerfile -t workadventure:front .`
2. Replace `image: thecodingmachine/nodejs:14` with `image: workadventure:front` in docker-compose.yaml

Nothing changed, the issue is still there. Whats the difference to the image on DockerHub?

**Comment by mielune** [comment]
Same issue here.

**Comment by mielune** [comment]
Same result with both images:
- image: thecodingmachine/nodejs:14
- image: thecodingmachine/workadventure-front:v1.1.0

**Comment by 4clu** [comment]
hey guys, 

the problem sounds interesting, could you find a solution, a way to solve it?

**Comment by loelkes** [comment]
I fixed it. The issue is not in the container but in the Traefik configuration:

You need to route 80/443 and 8080 to the front container. In the default config this is done by opening the webinterface `--api.insecure=true` and setting the entry point for the front container to Traefik. This means that the websocket is routed through the insecure API router. This failed for me because the insecure API was the first thing I removed since I don't need nor want it. I don't use the provided Traefik configuration, here's what I did:

Add an entry point in traefik.toml:
```
  [entryPoints.web_alt]
    address = ":8080"
```
and connect the `front` container with:
```
- "traefik.http.routers.front-ssl.entryPoints=websecure,web_alt"
```

**Comment by Informatic** [comment]
The *real* issue is that you're trying to run development instance publicly. We really need proper "minimal production" deployment setup.

**Comment by loelkes** [comment]
I don't like how you point at me for *trying* but no worries, I got what you said. Most of it is not documented or many things are built in a way that deploying it becomes a bit difficult. I've been working on and off on it and I will share what I did here, so we can move forward.

**Comment by loelkes** [comment]
The other, actually better fix, is to set the correct server URL in front/webpack.config.js from the environment variables. The [webpack documentation](https://webpack.js.org/configuration/dev-server/#devserverpublic) mentions that the scripts might wrongly guess the server URL if it's used behind a reverse proxy, which is the case here.

**Comment by 4clu** [comment]
thx @loelkes 
that is a nice tipp :o)

i can agree with you and @Informatic that we as a community need a step by step guide for an installation and configuration of wa (in a productive environment) so that we can avoid confusion in / with the documentation and frequently asked questions can be clarified without overloading the issues forum (maybe we also need a better community forum to organize projects, how to's) :)

#650 #683 #676 - same discussion
#578 #576 #577 - maybe a solution

**Comment by 4clu** [comment]
hi @loelkes 

> I fixed it. The issue is not in the container but in the Traefik configuration:
> 
> You need to route 80/443 and 8080 to the front container. In the default config this is done by opening the webinterface `--api.insecure=true` and setting the entry point for the front container to Traefik. This means that the websocket is routed through the insecure API router. This failed for me because the insecure API was the first thing I removed since I don't need nor want it. I don't use the provided Traefik configuration, here's what I did:
> 
> Add an entry point in traefik.toml:
> 
> ```
>   [entryPoints.web_alt]
>     address = ":8080"
> ```
> 
> and connect the `front` container with:
> 
> ```
> - "traefik.http.routers.front-ssl.entryPoints=websecure,web_alt"
> ```

do you know where is the traefik.toml is saved?
i search with find but i dont find nothing :(
e. g. `find /etc/ -name "traefik.toml"` , `find /home/workadventure -name "traefik.toml"`

and the line `- "traefik.http.routers.front-ssl.entryPoints=websecure,web_alt"` can add in the `docker-compose.yaml` by the section  >  `pusher:` > `labels:`?

and than we must edit the lines `docker-compose.yaml` ?
` --api.insecure=true` to `- --api.insecure=false`

and maybe we must edit in `docker-compose.yaml` ?
`      - --api.insecure=true`
`      - --providers.docker`
`      - --entryPoints.web.address=:80`
`      - --entryPoints.websecure.address=:443`
`     ports:`
`      - "80:80"`
`      - "443:443"`
`      # The Web UI (enabled by --api.insecure=true)`
`      - "8080:8080"`

**Comment by loelkes** [comment]
@4clu As said, I don't use the provided Traefik configuration. But with the pull request there's no need to change your configuration since the issue was fixed.

**Comment by mielune** [comment]
It due to the dev-mode, not the best for a 'prod' instance. It is the debug mode that's listening on 8080 and app tried to call with.
In `docker-compose.yaml`, replacing `NODE_ENV: development` by `NODE_ENV: production` may be so answer ?

I will try tomorrow.

**Comment by loelkes** [comment]
From what I see `NODE_ENV` is never checked... 🤷‍♂️ 

This has nothing to do with a dev-mode. The issue that the system is not aware of a reverse proxy, this can happen in both dev and production setups.

**Comment by 4clu** [comment]
hi there, i open a etherpad to gather points for a step by step guide for a workadventure productive env. 

https://pad.riseup.net/p/step_by_step_prod

feel free too add step's for a installation, configuration :-)

**Comment by moufmouf** [comment]
Hey @4clu ,

Thanks a lot for the etherpad.
In parallel, I built (on top of @Informatic PR #577) a PR to ease deployment => #698 .

It is still missing proper documentation, and the etherpad you started could definitely be this documentation.

I don't have too much time to work on the documentation but if anyone is interested, I gladly accept a PR on top of #698 to add this documentation.

**Comment by moufmouf** [comment]
I merged #698 that adds a sample `docker-compose.yml` file ready for production.

This should solve most of the problems people have.

I do agree it would be great to have a complete setup guide that also explains how to setup Jitsi, Coturn, etc... and the etherpad started by @4clu could be a good first step for this. This should probably be a blog article rather than part of this README?

Meanwhile, I'll close this issue as I believe #698 answers most of the questions asked here.
